import type { AppKey } from "@/lib/apps"

export const SECTION_DEFS = [
  { key: "CATALOGUING_AI",   label: "Cataloguing & AI" },
  { key: "BUSINESS_CENTRAL", label: "Business Central" },
  { key: "OPERATIONS",       label: "Operations" },
  { key: "AUCTION",          label: "Auction" },
  { key: "IT_ADMIN",         label: "IT & Admin" },
] as const

export type SectionKey = typeof SECTION_DEFS[number]["key"]

export type AppCardDef = {
  key: string
  href: string
  defaultLabel: string
  defaultDescription: string
  icon: string
  border: string
  iconBg: string
  btnBg: string
  glow: string
  group?: SectionKey  // undefined = standalone (rendered outside any section)
  appKey?: AppKey     // undefined = admin-only card
  allUsers?: boolean  // true = visible to all logged-in users regardless of role/apps
  comingSoon?: boolean
}

export const APP_CARD_DEFS: AppCardDef[] = [
  {
    key:                "CUSTOMERS",
    href:               "/contacts",
    defaultLabel:       "Customers",
    defaultDescription: "Unified customer database — view seller history, buyer activity, and contact details in one place.",
    icon:               "👥",
    border:             "border-green-500",
    iconBg:             "text-green-400",
    btnBg:              "bg-green-600 hover:bg-green-500",
    glow:               "hover:shadow-green-900/40",
    group:              "OPERATIONS",
    allUsers:           true,
  },
  {
    key:                "CRM",
    href:               "/submissions",
    defaultLabel:       "CRM",
    defaultDescription: "Manage customer submissions, valuations, follow-ups and logistics.",
    icon:               "📋",
    border:             "border-blue-500",
    iconBg:             "text-blue-400",
    btnBg:              "bg-blue-600 hover:bg-blue-500",
    glow:               "hover:shadow-blue-900/40",
    group:              "OPERATIONS",
    appKey:             "CRM",
  },
  {
    key:                "AUCTION_AI",
    href:               "/tools/auction-ai",
    defaultLabel:       "Auction AI",
    defaultDescription: "Generate lot descriptions from photos using Google Gemini AI.",
    icon:               "✨",
    border:             "border-amber-500",
    iconBg:             "text-amber-400",
    btnBg:              "bg-amber-600 hover:bg-amber-500",
    glow:               "hover:shadow-amber-900/40",
    group:              "CATALOGUING_AI",
    appKey:             "AUCTION_AI",
  },
  {
    key:                "CATALOGUING",
    href:               "/tools/cataloguing",
    defaultLabel:       "Cataloguing",
    defaultDescription: "Step-by-step lot cataloguing wizard — vendor, barcode, categories, estimates and condition.",
    icon:               "📂",
    border:             "border-teal-500",
    iconBg:             "text-teal-400",
    btnBg:              "bg-teal-600 hover:bg-teal-500",
    glow:               "hover:shadow-teal-900/40",
    group:              "CATALOGUING_AI",
    appKey:             "CATALOGUING",
  },
  {
    key:                "REPORTS",
    href:               "/tools/reports",
    defaultLabel:       "Reports",
    defaultDescription: "Performance reports — cataloguing speed, lots per day and team leaderboards.",
    icon:               "📊",
    border:             "border-teal-500",
    iconBg:             "text-teal-400",
    btnBg:              "bg-teal-600 hover:bg-teal-500",
    glow:               "hover:shadow-teal-900/40",
    group:              "CATALOGUING_AI",
    appKey:             "REPORTS",
  },
  {
    key:                "BC_REPORTS",
    href:               "/tools/bc-reports",
    defaultLabel:       "BC Reports",
    defaultDescription: "Business Central reporting — cataloguing, packing and warehouse.",
    icon:               "📊",
    border:             "border-red-500",
    iconBg:             "text-red-400",
    btnBg:              "bg-red-600 hover:bg-red-500",
    glow:               "hover:shadow-red-900/40",
    group:              "BUSINESS_CENTRAL",
    appKey:             "BC_REPORTS",
  },
  {
    key:                "BC_WAREHOUSE",
    href:               "/tools/bc-warehouse",
    defaultLabel:       "BC Warehouse",
    defaultDescription: "Business Central warehouse — location history, tote map and stock overview.",
    icon:               "🗺️",
    border:             "border-orange-500",
    iconBg:             "text-orange-400",
    btnBg:              "bg-orange-600 hover:bg-orange-500",
    glow:               "hover:shadow-orange-900/40",
    group:              "BUSINESS_CENTRAL",
    appKey:             "BC_WAREHOUSE",
  },
  {
    key:                "WAREHOUSE",
    href:               "/tools/warehouse",
    defaultLabel:       "Warehouse",
    defaultDescription: "Track containers, totes and warehouse locations.",
    icon:               "🏭",
    border:             "border-cyan-500",
    iconBg:             "text-cyan-400",
    btnBg:              "bg-cyan-600 hover:bg-cyan-500",
    glow:               "hover:shadow-cyan-900/40",
    group:              "OPERATIONS",
    appKey:             "WAREHOUSE",
  },
  {
    key:                "BC_API_VIEWER",
    href:               "/tools/bc-api-viewer",
    defaultLabel:       "BC API Viewer",
    defaultDescription: "Inspect field names and sample data from any Business Central endpoint.",
    icon:               "🔍",
    border:             "border-indigo-500",
    iconBg:             "text-indigo-400",
    btnBg:              "bg-indigo-600 hover:bg-indigo-500",
    glow:               "hover:shadow-indigo-900/40",
    group:              "BUSINESS_CENTRAL",
    appKey:             "BC_WAREHOUSE",
  },
  {
    key:                "ADMIN",
    href:               "/admin",
    defaultLabel:       "Admin",
    defaultDescription: "Manage users, departments and system settings.",
    icon:               "⚙️",
    border:             "border-slate-500",
    iconBg:             "text-slate-400",
    btnBg:              "bg-slate-600 hover:bg-slate-500",
    glow:               "hover:shadow-slate-900/40",
    group:              "IT_ADMIN",
    // no appKey — admin-only
  },
  {
    key:                "TICKETS",
    href:               "/tools/tickets",
    defaultLabel:       "Ticket System",
    defaultDescription: "Log IT problems and feature requests — track issues from open through to resolved.",
    icon:               "🎫",
    border:             "border-rose-500",
    iconBg:             "text-rose-400",
    btnBg:              "bg-rose-600 hover:bg-rose-500",
    glow:               "hover:shadow-rose-900/40",
    group:              "IT_ADMIN",
    allUsers:           true,
  },
  {
    key:                "IT_TOOLS",
    href:               "/tools/it-tools",
    defaultLabel:       "IT Tools",
    defaultDescription: "AI customer-email reply drafter + a library of pre-typed reply templates with one-click copy.",
    icon:               "🛠️",
    border:             "border-cyan-500",
    iconBg:             "text-cyan-400",
    btnBg:              "bg-cyan-600 hover:bg-cyan-500",
    glow:               "hover:shadow-cyan-900/40",
    group:              "IT_ADMIN",
    allUsers:           true,
  },
  {
    key:                "IT_HELP",
    href:               "/tools/it-help",
    defaultLabel:       "IT Help",
    defaultDescription: "Ask the IT chatbot — searches the knowledge base and resolved tickets for solutions to common problems.",
    icon:               "💡",
    border:             "border-yellow-500",
    iconBg:             "text-yellow-400",
    btnBg:              "bg-yellow-600 hover:bg-yellow-500",
    glow:               "hover:shadow-yellow-900/40",
    group:              "IT_ADMIN",
    allUsers:           true,
  },
  {
    key:                "DATABASES",
    href:               "/databases",
    defaultLabel:       "Databases",
    defaultDescription: "Search and manage all customers, receipts and totes in one unified place.",
    icon:               "🗄️",
    border:             "border-violet-500",
    iconBg:             "text-violet-400",
    btnBg:              "bg-violet-600 hover:bg-violet-500",
    glow:               "hover:shadow-violet-900/40",
    group:              "OPERATIONS",
    allUsers:           true,
  },
  {
    key:                "ACCOUNTS",
    href:               "#",
    defaultLabel:       "Accounts",
    defaultDescription: "Financial accounts, invoicing and vendor payments.",
    icon:               "💰",
    border:             "border-emerald-500",
    iconBg:             "text-emerald-400",
    btnBg:              "bg-emerald-600 hover:bg-emerald-500",
    glow:               "hover:shadow-emerald-900/40",
    group:              "OPERATIONS",
    allUsers:           true,
    comingSoon:         true,
  },
  {
    key:                "PACKING_DISPATCH",
    href:               "/tools/packing",
    defaultLabel:       "Packing / Dispatch",
    defaultDescription: "Create Royal Mail shipping labels and manage end-of-day manifests.",
    icon:               "📦",
    border:             "border-orange-500",
    iconBg:             "text-orange-400",
    btnBg:              "bg-orange-600 hover:bg-orange-500",
    glow:               "hover:shadow-orange-900/40",
    group:              "OPERATIONS",
    allUsers:           true,
  },
  {
    key:                "SALEROOM_TRAINER",
    href:               "/tools/saleroom-trainer",
    defaultLabel:       "Saleroom Trainer",
    defaultDescription: "Interactive training simulator for saleroom clerking.",
    icon:               "🎓",
    border:             "border-purple-500",
    iconBg:             "text-purple-400",
    btnBg:              "bg-purple-600 hover:bg-purple-500",
    glow:               "hover:shadow-purple-900/40",
    group:              "AUCTION",
    appKey:             "SALEROOM_TRAINER",
  },
  {
    key:                "WEBSITE",
    href:               "/website",
    defaultLabel:       "Website",
    defaultDescription: "View and manage the public auction website — browse live lots, published auctions and customer pages.",
    icon:               "🌐",
    border:             "border-sky-500",
    iconBg:             "text-sky-400",
    btnBg:              "bg-sky-600 hover:bg-sky-500",
    glow:               "hover:shadow-sky-900/40",
    group:              "AUCTION",
    allUsers:           true,
  },
  {
    key:                "AUCTION_CONTROLLER",
    href:               "/auction-controller",
    defaultLabel:       "Auction Controller",
    defaultDescription: "Live auction clerking panel — run bids, hammer lots, manage auto-bids and control the live sale.",
    icon:               "🔨",
    border:             "border-red-500",
    iconBg:             "text-red-400",
    btnBg:              "bg-red-600 hover:bg-red-500",
    glow:               "hover:shadow-red-900/40",
    group:              "AUCTION",
    appKey:             "AUCTION_CONTROLLER",
  },
  {
    key:                "AI_PRESENTER",
    href:               "/tools/avatar",
    defaultLabel:       "AI Presenter",
    defaultDescription: "Realistic AI avatar presenter — reads lot descriptions aloud with live lip-sync and head movement.",
    icon:               "🎙️",
    border:             "border-fuchsia-500",
    iconBg:             "text-fuchsia-400",
    btnBg:              "bg-fuchsia-600 hover:bg-fuchsia-500",
    glow:               "hover:shadow-fuchsia-900/40",
    group:              "AUCTION",
    appKey:             "AI_PRESENTER",
  },
  {
    key:                "AUCTION_MONITOR",
    href:               "/tools/auction-monitor",
    defaultLabel:       "Auction Monitor",
    defaultDescription: "Watch a live timed auction's WebSocket feed — stall detection, connection health and bid activity in real time.",
    icon:               "📡",
    border:             "border-emerald-500",
    iconBg:             "text-emerald-400",
    btnBg:              "bg-emerald-600 hover:bg-emerald-500",
    glow:               "hover:shadow-emerald-900/40",
    group:              "AUCTION",
    allUsers:           true,
  },
  {
    key:                "BC_MARKETING",
    href:               "/tools/bc-marketing",
    defaultLabel:       "BC Marketing",
    defaultDescription: "AI-powered marketing tools — generate SEO news articles from auction results.",
    icon:               "📰",
    border:             "border-pink-500",
    iconBg:             "text-pink-400",
    btnBg:              "bg-pink-600 hover:bg-pink-500",
    glow:               "hover:shadow-pink-900/40",
    group:              "BUSINESS_CENTRAL",
    appKey:             "BC_MARKETING",
  },
]
