// ISO alpha-2 → numeric (used to match world-atlas feature IDs)
export const ISO_NUMERIC: Record<string, string> = {
  AD: "20",  AE: "784", AR: "32",  AT: "40",  AU: "36",  BE: "56",
  BG: "100", BR: "76",  CA: "124", CH: "756", CN: "156", CY: "196",
  CZ: "203", DE: "276", DK: "208", EE: "233", ES: "724", FI: "246",
  FR: "250", GB: "826", GR: "300", HK: "344", HR: "191", HU: "348",
  IE: "372", IL: "376", IN: "356", IS: "352", IT: "380", JP: "392",
  KR: "410", LI: "438", LT: "440", LU: "442", LV: "428", MC: "492",
  MT: "470", MX: "484", MY: "458", NL: "528", NO: "578", NZ: "554",
  PL: "616", PT: "620", RO: "642", RS: "688", RU: "643", SA: "682",
  SE: "752", SG: "702", SI: "705", SK: "703", TH: "764", TR: "792",
  TW: "158", UA: "804", UK: "826", US: "840", ZA: "710",
}

export const COUNTRY_NAMES: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BE: "Belgium",
  BG: "Bulgaria",
  BR: "Brazil",
  CA: "Canada",
  CH: "Switzerland",
  CN: "China",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DK: "Denmark",
  EE: "Estonia",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "United Kingdom",
  GR: "Greece",
  HK: "Hong Kong",
  HR: "Croatia",
  HU: "Hungary",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IS: "Iceland",
  IT: "Italy",
  JP: "Japan",
  KR: "South Korea",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  MC: "Monaco",
  MT: "Malta",
  MX: "Mexico",
  MY: "Malaysia",
  NL: "Netherlands",
  NO: "Norway",
  NZ: "New Zealand",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  SA: "Saudi Arabia",
  SE: "Sweden",
  SG: "Singapore",
  SI: "Slovenia",
  SK: "Slovakia",
  TH: "Thailand",
  TR: "Turkey",
  TW: "Taiwan",
  UA: "Ukraine",
  UK: "United Kingdom",
  US: "United States",
  ZA: "South Africa",
  // UK Crown Dependencies / territories
  NI: "Northern Ireland",
  GG: "Guernsey",
  JE: "Jersey",
  IM: "Isle of Man",
  GI: "Gibraltar",
  // Rest of geographic Europe not already listed
  AL: "Albania",
  AX: "Aland Islands",
  BA: "Bosnia and Herzegovina",
  BY: "Belarus",
  FO: "Faroe Islands",
  GL: "Greenland",
  MD: "Moldova",
  ME: "Montenegro",
  MK: "North Macedonia",
  SM: "San Marino",
  VA: "Vatican City",
  // Common Rest-of-World destinations seen in BC data
  ID: "Indonesia",
  OM: "Oman",
  GQ: "Equatorial Guinea",
  NG: "Nigeria",
  PH: "Philippines",
  VN: "Vietnam",
  EG: "Egypt",
  KE: "Kenya",
  PK: "Pakistan",
  QA: "Qatar",
  KW: "Kuwait",
  BH: "Bahrain",
  LK: "Sri Lanka",
  CL: "Chile",
  CO: "Colombia",
  MA: "Morocco",
  JO: "Jordan",
  LB: "Lebanon",
}

// BC sometimes emits a non-canonical code for the same place. Map it to the
// canonical alpha-2 so the report doesn't show a duplicate country row (e.g.
// "United Kingdom (GB)" AND "United Kingdom (UK)").
export const COUNTRY_ALIASES: Record<string, string> = { UK: "GB" }

// Reverse map: lowercase full name → alpha-2 (for BC data that sends full names)
export const NAME_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_NAMES)
    .filter(([k]) => k !== "UK") // dedupe UK/GB — GB wins
    .map(([a2, name]) => [name.toLowerCase(), a2])
)
