// Default cataloguing category → subcategory map. This is the SEED + fallback only:
// the live list is stored in the DB (LotCategory / LotSubcategory) and managed at
// /admin/categories. This file has NO prisma import so it's safe in client bundles
// (the cataloguing dropdowns import it as the instant fallback before they fetch
// the DB copy from /api/catalogue/categories).
export const DEFAULT_CATEGORY_MAP: Record<string, string[]> = {
  "BEARS": [
    "ACCESSORIES", "ARTIST", "COLLECTOR_BOOKS", "DISNEYANA", "FIGURES", "FIGURES_STORAGE", "MAKING_SUPPLIES",
    "MINIATURES", "MIXED_LOTS", "MODERN", "OTHER_ITEMS", "VINTAGE"
  ],
  "COLLECTABLES": [
    "ADVERTISING", "ANIMAL", "BADGES", "BOTTLES_POTS", "BREWERIANA", "CASINO", "DECORATIVE", "EPHEMERA",
    "FANTASY", "HISTORICAL", "HOME", "JEWELLERY", "KEYRINGS", "LIGHTING", "MASONIC", "MEMORABILIA",
    "METALWARE", "MILITARIA", "MILITARIA MEDALS", "MONEYBOXES", "NUMISMATIC", "OTHER", "PEZ", "PHOTOS",
    "POSTCARDS", "RADIO_TV_PHO", "RELIGION", "SCIENTIFIC", "SEASONAL", "SEWING", "TEA & CIGERATTE",
    "TEXTILES", "TOBACCIANA", "TOOLS", "TOYS", "VANITY", "WATCHES", "WRITING"
  ],
  "DOLLS": [
    "ACCESSORIES", "ANTIQUE", "ARTIST", "BLYTHE", "BOOKS", "COLLECTOR_BOOKS", "FASHION", "GOLLIES",
    "HOUSE_FIGURES", "HOUSE_FURNITURE", "HOUSES", "MODERN", "REPAIR", "VINTAGE"
  ],
  "GAMING": [
    "ACCESSORIES", "ARCADE MACHINES", "COIN_OPERATED", "COMPUTERS", "CONSOLES", "ELECTRONIC GAMES",
    "HANDHELD CONSOLES", "MERCHANDISE", "VIDEO_GAMES"
  ],
  "KITS": [
    "KITS_AIRCRAFT", "KITS_AUTOMOTIVE", "KITS_BOATS_SHIPS", "KITS_BUILDINGS", "KITS_DIORAMAS",
    "KITS_FIGURES", "KITS_MILITARY", "KITS_OTHER", "KITS_PUBLICATIONS", "KITS_SPACECRAFT",
    "KITS_TOOLS_SUPPLIES"
  ],
  "MILITARY": [
    "1/6 SCALE FIGURES", "AIRFIX", "ALBA MINIATURES", "BENBROS", "BLENHEIM", "BOOKS", "BRITAINS ACW (LEAD)",
    "BRITAINS ACW PLASTIC", "BRITAINS CIVILIAN", "BRITAINS COWBOYS", "BRITAINS DEETAIL",
    "BRITAINS DELHI DURBA", "BRITAINS EYES RIGHT", "BRITAINS FARM", "BRITAINS FLORAL", "BRITAINS FOOTBALL",
    "BRITAINS HERALD", "BRITAINS HOME FARM", "BRITAINS LILLIPUT", "BRITAINS MEDIEVAL",
    "BRITAINS METAL MODEL", "BRITAINS MILITARY", "BRITAINS MINI GARDEN", "BRITAINS MOTORCYCLES",
    "BRITAINS NAPOLEONIC", "BRITAINS NOVELTY", "BRITAINS PREMIER", "BRITAINS RACING COL",
    "BRITAINS REGIMENTS", "BRITAINS ROAD", "BRITAINS SOLDIERS", "BRITAINS SWOPPETS", "BRITAINS VINTAGE",
    "BRITAINS WWI", "BRITAINS WWII", "BRITAINS ZOO", "BRITAINS ZOO (LEAD)", "BRITAINS ZOO-PLASTIC",
    "BRITAINS ZULU WARS", "C.B.G. MIGNOT", "CHARBENS", "CHERILEA", "CIVILIAN", "COLLECTORS SHOWCASE",
    "CORGI", "COWBOYS & INDIANS", "CRESCENT", "DEL PRADO OR SIMILAR", "DIORAMAS / SCENERY",
    "DORSET SOLDIERS", "DRAGON IN DREAM", "DUCAL", "ELASTOLIN", "FIGURES", "FIRST LEGION", "FORCES OF VALOR",
    "FRONTLINE FIGURES", "HEYDE", "HISTOREX", "HUGAR", "JOHILLCO", "JOHN JENKINS", "KEYMEN",
    "KING & COUNTRY", "KING & COUNTRY ACW", "KING & COUNTRY HK", "KING & COUNTRY NAP", "KING & COUNTRY WWI",
    "KING & COUNTRY WWII", "KIT FIGURES METAL", "KIT FIGURES RESIN", "LINEOL & ELASTOLIN", "LONE STAR",
    "LUCOTTE", "MÄRKLIN", "MIXED LEAD FIGURES", "MIXED PLASTIC FIGURE", "MKL MODELS", "NIENA", "ORYON",
    "OTHER", "OTHER PLASTIC", "PHILLIP SEGAL", "PIXYLAND-KEW", "SACUL", "SILVER DREAM STUDIOS",
    "SOLID FIGURES", "STADDEN", "STARLUX", "STEADFAST SOLDIERS", "TAYLOR & BARRETT", "THOMAS GUNN",
    "THOMAS GUNN WWII", "TIMPO LEAD", "TIMPO PLASTIC", "TIMPO ROMANS", "TIMPO WILD WEST", "TINPLATE",
    "TOY SOLDIER CENTRE", "TOY SOLDIERS", "TRADITION", "TRIANG", "TROPHY MINIATURES", "UNDER TWO FLAGS",
    "VERO", "WARGAMING", "WATERLINE SHIPS", "WEND-AL, QUIRALU"
  ],
  "MATCHBOX": [
    "ACCESSORIES", "COLLECTIBLES", "CONVOY", "DINKY_COLLECTION", "KING_SIZE", "MIXED", "MOY",
    "OTHER_MATCHBOX", "POS_PROMO", "REGULAR_MOKO", "SKYBUSTERS", "SUPER_& SPEED_KINGS", "SUPERFAST"
  ],
  "MODELS_KITS": [
    "AIRCRAFT", "BOATS", "DRONES", "MODEL_KITS", "OTHER", "RC_ACCESSORIES", "RC_TOYS", "RC_VEHICLES",
    "TETHER_CARS"
  ],
  "MODERN_DIECAST": [
    "ACCESSORIES", "AIRCRAFT", "MOTORBIKES", "PLANES AND VEHICLES", "VEHICLES", "WHITE_METAL_RESIN"
  ],
  "MUSIC_MEDIA": [
    "ACCESSORIES", "BLURAY_DVD_VIDEO", "CASSETTES", "CDS", "MEMORABILIA", "OTHER", "VINYL_RECORDS"
  ],
  "PUBLICATIONS": [
    "ANTIQUARIAN", "ARTBOOKS", "BOOKS", "CATALOGUES", "COM_ART", "COMICS", "FAN_ZINES", "HISTORICAL",
    "MAGAZINES", "MANGA", "MERCHANDISE", "PRICE_GUIDES", "TOY REFERENCE BOOKS"
  ],
  "RETRO_TOYS": [
    "ACTION_MAN", "CYCLES", "LEGO", "LEGO ARCHITECTURE", "LEGO BOTANICAL", "LEGO BRICK HEADZ", "LEGO CITY",
    "LEGO CREATOR", "LEGO DC", "LEGO FRIENDS", "LEGO GAMING", "LEGO HARRY POTTER", "LEGO ICONS",
    "LEGO IDEAS", "LEGO LOOSE PARTS", "LEGO MARVEL", "LEGO MINIFIGURES", "LEGO NINJAGO", "LEGO SPACE",
    "LEGO SPEED CHAMPIONS", "LEGO STAR WARS", "LEGO TECHNIC", "LEGO TRAINS", "LEGO TV / FILM",
    "LEGO TV/FILM", "LEGO VEHICLES", "LEGO VINTAGE", "OTHER", "PLAYMOBIL", "SCALEXTRIC_SLOT", "SKATEBOARDS",
    "SUBBUTEO"
  ],
  "SPORTS": [
    "AMERICAN_FOOTBALL", "BOXING", "CRICKET", "FOOTBALL_MEMORABILIA", "FOOTBALL_PROGRAMMES",
    "FOOTBALL_SHIRTS", "GOLF", "HOCKEY", "MOTOR_SPORT", "OLYMPICS", "OTHER", "RACING", "RUGBY_LEAGUE",
    "RUGBY_UNION", "SPORTS_STICKERS", "TENNIS", "TRADING_CARDS", "WRESTLING"
  ],
  "STAR_WARS": [
    "ACTION_FIGURES", "AUTOGRAPHS", "BOOKS", "BOXED_ACCESSORIES", "BOXED_FIGURES_12", "CARDED_GRADED",
    "CARDED_UNGRADED", "CLOTHING", "COLLECTOR_PLATES", "DIECAST_MICRO", "FIGURINES", "GRADED_FIGURES_12",
    "LOOSE_ACCESSORIES", "LOOSE_FIGURES_12", "LOOSE_FIGURES_GRADED", "LOOSE_FIGURES_UNGRAD", "MERCHANDISE",
    "OTHER", "PLAYSETS", "POSTERS", "PROMOTIONAL", "VEHICLES", "WEAPON_REPLICAS"
  ],
  "TOY_FIGURES": [
    "ANIMALS_CHARACTERS", "CLOTHING", "OTHER", "ROLEPLAYING", "SOLDIERS"
  ],
  "TRADING_CARDS": [
    "ACCESSORIES", "BOX_BREAKS", "BOXES", "CARD_SHEETS", "CASES", "DECKS", "GRADED_CARDS", "INDIVIDUAL",
    "MIXED_LOTS", "PACKS", "PLAYER_BUILT_DECKS", "PUBLICATIONS", "SETS", "THEME DECKS", "TINS"
  ],
  "TRAINS": [
    "BACHMANN", "BACHMANN_BRANCHLINE", "BASSETT_LOWKE_O", "DAPOL_O", "DAPOL_OO", "FLEISCHMANN_HO",
    "G_GAUGE_GARDEN_RAIL", "GAUGE_1_LARGER", "GENERAL_TRAIN", "HELJAN_O", "HELJAN_OO", "HO_USA_CONTINENTAL",
    "HORNBY_ACHO", "HORNBY_CHINA", "HORNBY_DUBLO_2_3RAIL", "HORNBY_GB", "HORNBY_O_GAUGE", "HORNBY_TRIANG",
    "LILIPUT", "LIMA", "LIVE_STEAM", "MIXED", "MODERN_O_GAUGE", "N_GAUGE", "NARROW_GAUGE",
    "O_GAUGE_KIT_KITBUILT", "OO_GAUGE_BRITISH_OUT", "OO_GAUGE_KIT_KITBUIL", "OTHER_O_GAUGE", "RAILWAYANA",
    "RIVAROSSI", "SETS", "TRIANG_RAILWAYS", "TRIX_TWIN", "WRENN_RAILWAYS", "Z_GAUGE"
  ],
  "TV_FILM": [
    "ACTION_FIGURES", "AUTOGRAPHS", "BOARD_GAMES", "CLOTHING", "FIGURINES", "FILM_CELLS", "ORNAMENTS",
    "OTHER", "PHOTOGRAPHS", "PLAY_SETS", "POSTERS", "VEHICLE_REPLICAS"
  ],
  "VINTAGE_DIECAST": [
    "ACCESSORIES", "AIRCRAFT", "VEHICLES"
  ],
  "VINTAGE_TOYS": [
    "AUTOMATONS", "CONSTRUCTION", "GAMES", "NOAHS_ARKS", "OTHER", "PUPPETS", "ROBOTS", "ROCKING_HORSES",
    "TINPLATE"
  ],
}
